### PR TITLE
Added user related API endpoint tests.

### PR DESCRIPTION
**Pull request by NickWu007**
Added tests for following endpoints:

 * `api/user/login`
 * `api/user/update`

A snapshot of test run:

~~~bash
$ npm test

> trylinks-server@0.0.0 test /Users/NickWu/Developer/TryLinks/server/trylinks-server
> mocha "test/*.js"



  User login
    Tests for unauthenticated endpoints
      ✓ should login with correct username (125ms)
      ✓ should return error with non-existent username
      ✓ should return error with incorrect username and password (103ms)
      ✓ should not update user unless authenticated
    Tests for authenticated endpoints
      ✓ should update user after authenticated (112ms)


  5 passing (357ms)
~~~

### CODE REVIEW

**Comment by jamescheney** [comment]
This all looks fine to me.  My knowledge of JavaScript is extremely basic though.

**Comment by NickWu007** [comment]
In that case I will only request Arek for review, thanks for letting me know.

**Comment by jamescheney** [comment]
I'm happy to look at things, but it's definitely fine not to wait for me!

**Comment by NickWu007** [comment]
OK got it

**Pull request merged**
